checks:
    python:
        code_rating: true
        duplicate_code: true

tools:
    pylint:
        python_version: '3'
        config_file: pylintrc

filter:
    excluded_paths:
        - test/*

build:
    dependencies:
        before:
            -
                command: pip3 install coverage
    tests:
        override:
            -
                command: coverage run -m unittest discover -s test -p *Test.py
                coverage:
                    file: '.coverage'
                    config_file: '.coveragerc'
                    format: 'py-cc'
