checks:
    python:
        code_rating: true
        duplicate_code: true
tools:
    pylint:
        python_version: '3'
        config_file: pylintrc
filter:
    excluded_paths:
        - test/*
        - sdoc/antlr/*

build:
    tests:
        override:
            -
                command: python -m unittest discover -s test -p *Test.py